package bfbf.palindromes;

/**
 * An abstract class representing BFB palindromes, i.e. palindromes
 * which may be generated by a sequence of BFB cycles.
 */
public abstract class BFBPalindrome extends Palindrome {

    protected BFBPalindrome(Palindrome center, Palindrome wrap) {
        super(center, wrap);
    }

    /**
     * For a BFB palindrome with base segment index l+1, returns the l-block
     * obtained by wrapping this palindrome with l-segments.
     *
     * @return the block corresponds to the wrapping of this palindrome
     */
    public Block wrap() {
        return Block.make(this);
    }


}
